package de.hdm_stuttgart.mi.dbad.dbwarp.model.column;

/*-
 * #%L
 * DBWarp
 * %%
 * Copyright (C) 2024 Kay Knöpfle, Lucca Greschner and contributors
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

public enum GenerationStrategy {
  /**
   * The column is not generated
   */
  NONE,
  /**
   * The column is automatically incremented by a sequence. If rows are deleted, the values are not
   * guaranteed to be unique (i.e. deleted values may be reused)
   */
  SERIAL,
  /**
   * The column is generated by a sequence, and it is guaranteed that the values are unique even if
   * rows are deleted
   */
  IDENTITY
}
