---
-- #%L
-- DBWarp
-- %%
-- Copyright (C) 2024 Kay Knöpfle, Lucca Greschner and contributors
-- %%
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public
-- License along with this program.  If not, see
-- <http://www.gnu.org/licenses/gpl-3.0.html>.
-- #L%
---
-- GENERATED ALWAYS means that the column is automatically generated and cannot be overridden by the user.
CREATE TABLE GeneratedAlwaysTestTable
(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
);

-- GENERATED BY DEFAULT means that the column is automatically generated, but the value can be overridden by the user.
CREATE TABLE GeneratedByDefaultTestTable
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

-- SERIAL is a (legacy) shorthand for GENERATED BY DEFAULT AS IDENTITY
CREATE TABLE SerialTestTable
(
    id SERIAL PRIMARY KEY
);
