-- GENERATED ALWAYS means that the column is automatically generated and cannot be overridden by the user.
CREATE TABLE GeneratedAlwaysTestTable
(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
);

-- GENERATED BY DEFAULT means that the column is automatically generated, but the value can be overridden by the user.
CREATE TABLE GeneratedByDefaultTestTable
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

-- SERIAL is a (legacy) shorthand for GENERATED BY DEFAULT AS IDENTITY
CREATE TABLE SerialTestTable
(
    id SERIAL PRIMARY KEY
);